version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: afisliteadmin
      POSTGRES_PASSWORD: afisliteadmin
      POSTGRES_DB: afislite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  broker_api:
    image: afislitebrokerapi:latest
    container_name: broker_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: afislite
      DB_PASSWORD: afisliteadmin
      DB_NAME: afisliteadmin
    ports:
      - "8080:8080"
    
volumes:
  postgres_data: